# Generated by Django 2.2.5 on 2019-09-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('add_date', models.DateTimeField()),
                ('sgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Grade')),
            ],
        ),
    ]
